---
notifications:
  email:
    - slyphon@gmail.com
    - eric@5stops.com

# pull in releaseops submodule
before_install:
  - git submodule update --init --recursive

env:
  - SPAWN_ZOOKEEPER='true'

language: ruby

rvm:
  - ree
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - 1.9.3
  - 2.0.0
  - 2.1.10
  - 2.2.10
  - 2.3.8
  - 2.4.9
  - 2.5.7
  - 2.6.5
matrix:
  allow_failures:
    - rvm: rbx-18mode
    - rvm: rbx-19mode

bundler_args: --without development docs coverage

# blacklist
branches:
  except:
#     - 'dev/zookeeper-st'
